"""
bonus/agent.py — HybridMemoryAgent

A minimal POC combining:
- Episodic memory (Qdrant vector store)
- Stable user profile (Feast feature store)

This is the skeleton. Boilerplate generated by vibe-coding;
architecture decisions (collection naming, payload schema, retrieval strategy)
are intentional and documented in ARCHITECTURE.md.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Optional

from feast import FeatureStore
from fastembed import TextEmbedding
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, PointStruct, VectorParams, Filter, FieldCondition, MatchValue


class HybridMemoryAgent:
    """
    Personal AI assistant với hybrid memory:
    - Episodic: conversations, documents, notes → Qdrant
    - Stable: user profile, preferences → Feast

    Usage:
        agent = HybridMemoryAgent()
        agent.remember("User asked about Kubernetes deployment", user_id="u_001")
        context = agent.recall("What did I ask about recently?", user_id="u_001")
    """

    COLLECTION_NAME = "hybrid_memory"
    EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"
    VECTOR_DIM = 384

    def __init__(
        self,
        feast_repo: str = "app/feast_repo",
        qdrant_client: Optional[QdrantClient] = None,
    ):
        """
        Initialize both storage layers.

        Args:
            feast_repo: Path to Feast repository (for feature store).
            qdrant_client: Qdrant client instance.
                           If None, creates in-memory client.
        """
        # ── Vector store (episodic memory) ─────────────────────────────────
        self._qdrant = qdrant_client or QdrantClient(":memory:")
        self._embedder = TextEmbedding(model_name=self.EMBEDDING_MODEL)
        self._ensure_collection()

        # ── Feature store (stable profile) ──────────────────────────────────
        self._feast = FeatureStore(repo_path=feast_repo)

    def _ensure_collection(self) -> None:
        """Create Qdrant collection if it doesn't exist."""
        collections = [c.name for c in self._qdrant.get_collections().collections]
        if self.COLLECTION_NAME not in collections:
            self._qdrant.create_collection(
                collection_name=self.COLLECTION_NAME,
                vectors_config=VectorParams(
                    size=self.VECTOR_DIM,
                    distance=Distance.COSINE,
                ),
            )

    # ── Episodic Memory ───────────────────────────────────────────────────────

    def remember(self, text: str, user_id: str = "u_001", source: str = "conversation") -> str:
        """
        Add a new piece of episodic memory for this user.

        Args:
            text: The memory content (conversation, document, note, etc.)
            user_id: Which user this memory belongs to.
            source: Where this memory came from (e.g. "conversation", "document", "note")

        Returns:
            memory_id: UUID of the stored memory.
        """
        memory_id = str(uuid.uuid4())
        timestamp = datetime.now(timezone.utc).isoformat()

        # 1. Embed the text
        vector = next(self._embedder.embed([text])).tolist()

        # 2. Build payload
        payload = {
            "memory_id": memory_id,
            "user_id": user_id,
            "content": text,
            "source": source,
            "timestamp": timestamp,
        }

        # 3. Upsert to Qdrant
        point = PointStruct(
            id=memory_id,
            vector=vector,
            payload=payload,
        )
        self._qdrant.upsert(collection_name=self.COLLECTION_NAME, points=[point])

        return memory_id

    def recall(
        self,
        query: str,
        user_id: str = "u_001",
        top_k: int = 5,
    ) -> str:
        """
        Retrieve top-K memories + user profile → assembled context string.

        This method:
        1. Gets user profile from Feast (fast, structured)
        2. Hybrid-searches Qdrant for relevant episodic memories (filtered by user_id)
        3. Assembles a context string for the LLM

        Args:
            query: User's current question or information need.
            user_id: Which user's memories and profile to use.
            top_k: How many episodic memories to retrieve.

        Returns:
            A context string ready to be injected into the LLM prompt.
        """
        # ── 1. Feature store: user profile ───────────────────────────────────
        features = self._feast.get_online_features(
            features=[
                "user_profile_features:topic_affinity",
                "user_profile_features:reading_speed_wpm",
                "user_profile_features:preferred_language",
                "query_velocity_features:queries_last_hour",
                "query_velocity_features:distinct_topics_24h",
            ],
            entity_rows=[{"user_id": user_id}],
        ).to_dict()

        topic_affinity = features.get("topic_affinity", [None])[0]
        reading_speed = features.get("reading_speed_wpm", [None])[0]
        preferred_lang = features.get("preferred_language", [None])[0]
        queries_1h = features.get("queries_last_hour", [None])[0]
        topics_24h = features.get("distinct_topics_24h", [None])[0]

        # ── 2. Vector store: episodic memories ──────────────────────────────
        q_vec = next(self._embedder.embed([query])).tolist()

        results = self._qdrant.query_points(
            collection_name=self.COLLECTION_NAME,
            query=q_vec,
            query_filter=Filter(
                must=[
                    FieldCondition(
                        key="user_id",
                        match=MatchValue(value=user_id),
                    )
                ]
            ),
            limit=top_k,
        )

        memories = []
        for hit in results.points:
            p = hit.payload
            memories.append(
                f"[{p.get('source', 'unknown')}] {p.get('content', '')}"
            )

        # ── 3. Assemble context string ────────────────────────────────────
        parts = []

        if topic_affinity:
            parts.append(f"User likes <{topic_affinity}> reading at <{reading_speed}>wpm "
                        f"(prefers {preferred_lang})")

        if queries_1h is not None:
            parts.append(f"Recent activity: <{queries_1h}> queries in the last hour, "
                        f"<{topics_24h}> distinct topics in 24h")

        if memories:
            parts.append(f"Top memories: {' | '.join(memories[:3])}")
        else:
            parts.append("No memories yet for this user.")

        return " ".join(parts)


# ── Quick smoke test ────────────────────────────────────────────────────────

if __name__ == "__main__":
    import time

    agent = HybridMemoryAgent()

    # Seed some memories
    agent.remember(
        "User asked about Kubernetes autoscaling configuration",
        user_id="u_001",
        source="conversation",
    )
    agent.remember(
        "User read an article about cloud cost optimization using spot instances",
        user_id="u_001",
        source="document",
    )
    agent.remember(
        "User asked about CI/CD pipeline setup with GitHub Actions",
        user_id="u_001",
        source="conversation",
    )

    # Recall test
    context = agent.recall("What did I ask about recently?", user_id="u_001", top_k=3)
    print("Context assembled:", context)
    print("\n✅ HybridMemoryAgent smoke test passed")
